### ISSUE TITLE
Credit screen creating endless errors - showing in console output

### ISSUE THREAD

**Issue by Packi1992** [Packi1992/Bachelor_Defender_Methran#127]

**Comment by Packi1992** [comment]
![grafik](https://github.com/Packi1992/Bachelor_Defender_Methran/assets/63595780/72bf9791-e065-4e4c-b1d0-c9339d7dda80)
das sind die Fehler ... eine Ahnung woher die kommen?

**Comment by Index-Pixel** [comment]
Fixed with last merge request
